@startuml Anwendungskern

!pragma useNewPackage
skinparam classAttributeIconSize 2
skinparam componentStyle uml2

package mongoose {
  class Schema

  class "model()" as model
  hide model circle
}
package song.entity {
  class "Song" as Song {
    id?: string
    name: string
    laenge: string
  }
}

package album.entity {
  class "validateAlbum()" as validateAlbum
  hide validateAlbum circle

  class AlbumModel
  hide AlbumModel circle

  AlbumModel ..> Schema
  AlbumModel ..> model
  AlbumModel ..> validateAlbum

  AlbumData ..> Interpret
  AlbumData ..> Label
  AlbumData *-- Song

  enum Interpret {
    TRIVIUM
    FIVEFINGERDEATHPUNCH
	  ZUGEZOGENMASKULIN
  	DENDEMANN
  }

  enum Label {
    SONY_MUSIC
    ROADRUNNER_RECORDS
	  BETTERNOISE_MUSIC
	  UNIVERSAL_MUSIC
  }

  interface AlbumData <<entity>> {
    + _id?: string
    + __v?: number
    + createdAt?: number
    + updatedAt?: number
    + name: string
    + interpret: Interpret
    + label: Label
    + trackliste: Array<Song>
    + lauflänge: 
    + produzent: string
  }
}

hide empty members

footer (c) Alexander Mader, Matthias Treiste, Glynis Zolk

@enduml