@startuml Use Cases

left to right direction
skinparam packageStyle rect
skinparam componentStyle uml2

actor Kunde
actor Admin

rectangle kunde {
    Kunde --> (Song suchen)
    Kunde --> (Song herunterladen)
    Kunde --> (Song herunterladen)
    Admin --> (Song suchen)
    Admin --> (Song anlegen)
    Admin --> (Song ändern)
    Admin --> (Song löschen)
    Admin --> (Song hochladen)
    Admin --> (Song herunterladen)
    Admin --> (Song hochladen)
    Admin --> (Song herunterladen)
}

footer (c) Alexander Mader, Matthias Treise, Glynis Zolk

@enduml